### ISSUE TITLE
Blog post content width is fairly narrow

### ISSUE THREAD

**Issue by melanierichards** [riverar/blogs.windows.com-issues#11]
*For transparency, I both contribute to a Windows blog (Microsoft Edge) and read blog posts.*

When reading a blog post within a fairly large window (here I am at ~1200px wide), the column width for body text is pretty narrow:

<img width="888" alt="Screenshot of blog post content showing about 6 words per line" src="https://user-images.githubusercontent.com/340395/93518162-4e1bdb80-f8e1-11ea-9b47-4dbb41df8cf8.png">

I personally find it difficult to read line lengths at this width, particularly if it's a longer format blog post, such as [the post I've pulled a screenshot from](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/).

Within the site's CSS framework, I think this could be pretty quickly resolved by swapping out `.l-container--small` for `.l-container--medium` on the post content container. Those container classes rely on percentage lengths, so another option would be to instead switch to a relative `max-width`, maybe something like `42rem`.

Thanks for opening up this issue forum and providing a place to leave suggestions!

**Comment by riverar** [comment]
Seems they increased the width, what do you think? I'm torn, still feels like some work can be done here but does appear the issue was more/less resolved.

![image](https://user-images.githubusercontent.com/475132/98089891-34563980-1e38-11eb-9011-f98e7695e4d7.png)

**Comment by melanierichards** [comment]
Hi @riverar, sorry I missed your follow-up! I'll close my issue since I think the root problem here has been addressed, and perhaps a new one can be opened for any further optimizations?
